os: linux
dist: trusty
language: android
jdk: oraclejdk8

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

addons:
  apt:
    # Flutter dependencies
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support

cache:
  directories:
  - vendor/bundle
  - "$HOME/flutter/"

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager ndk-bundle
  - gem install fastlane
  - if [ ! -d "${HOME}/flutter/bin" ]; then rm -rf ${HOME}/flutter; git clone https://github.com/flutter/flutter.git -b stable --depth 1 ${HOME}/flutter; fi
  - cd cruzall
  - ${HOME}/flutter/bin/flutter upgrade
  - ${HOME}/flutter/bin/flutter doctor
  - ${HOME}/flutter/bin/flutter packages get
  - ${HOME}/flutter/bin/flutter packages pub run build_runner build
  - cd cruzawl
  - ${HOME}/flutter/bin/flutter packages get
  - ${HOME}/flutter/bin/flutter packages pub run build_runner build
  - cd ../..

before_script:
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in travis-ci-apk-upload.json.enc -d -a -out travis-ci-apk-upload.json
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in cruzall/android/Cruzall_Distribution.keystore.enc -d -a -out cruzall/android/Cruzall_Distribution.keystore
  - echo storePassword=$KEYSTORE_PASSWORD >> cruzall/android/key.properties
  - echo keyPassword=$KEY_PASSWORD >> cruzall/android/key.properties

script:
  - cd cruzall
  - ${HOME}/flutter/bin/flutter -v build apk --release
  - cd ..
  - md5sum cruzall/build/app/outputs/apk/release/app-release.apk
  - fastlane submit_playalpha

after_success:
  - echo "success"

after_failure:
  - echo "failure"

env:
  global:
  - TERM=dumb
  - secure: KKwxo4IyR0VYwCFhp+epX4sdncgZpuQ7aVessk2AlkjIKajmOFVJCXcOV0H23rH44dPEI1Mc09T0KJ+DpAJP5mMIkZ8HOPbR9QQcrL+B82nkUxPFW/vzT12DaY8Kx42TJ9/0LUSVGq+o/0YCGj432jpRX7jx6BevSkJA2ppyh0knvcQvKxSm8fujmXnsyofmvxYY5hoXR+nhfhrrWcFsA2z+drBAkMJJxmERxL2RlM+QzfsgLQF8gp1ahZ5l1ah/RmJwrdA1PjoztU2TClheim6zCLrAekw0SCf+sBpJvK0HX2K2f/V4SWaA1/zrtB8XyYVabJ+BWO57MNguPF4bAL+tz5RDLKwnXvAFoD8PNAW3BNsLPP7Ig65EXZK0bIKuVcXKvu0QGgfVgVJ+cizHINL4l7rq3DnzoCXn0C56W01awcai8Q7qyaM0DQb97a2NBZOoMsp2Fvz6daYZYDT5EG8fOfoFLZPqqkmz/AoK3RX26qSUnMqGfVFAidXHBfG9e01jKk53ajYrz/9SL+zGiNifiN7itXD+vn+0Fl39CNW0rx/LpLHdKHQe/PHPP7manUb3S7ZQj8e8rNMvd9f/SNXIg/kyws4qWzPIa+SitlO6eBaGjfR707ZPAo/e55KR8KaZ+c7kLrnNsY7uXjRt6asUYaYZ4wODNk3mChArqx0=
  - secure: DorT5ajcuhu0eehOGDWAZoMoOBr2oPKROGyYDzEqbWJYY+R2vqalvXJ84/duPcA8mW2n+O/+nFr/9yjudWfgPjPnG1UWzo0pxAvT6yYfpp2G9e2FnQ42blj2d5AsdSuxjhT/SuIgRQLnRlu5qnNi/g4L6OpZxw9z35GC0ZPrY0DuP0zbyCp3QjMxprZAQHu2sC+UV6o8lknipQOOhf5jgik2tKv/m2H4HZGAybP1L89t4hhQM2egPcew0T6kXuSuhh/woe5g2pz1LE4SeK54NrzSOCSx5Cgi+m9VDqW5bqtb+j9hJx6nJ7VbkalrXRoKbLIEh/CooYASpiXc/RObgV9MjziOhf3BvQSR8tT/zP3JybYWi34P29F7IXlEfcElpo75f8/N/xJ6kGV1VFrT1KTDDX3xp62I1U2EiX6LhbJomdDZH0xA8Dt9iDUJUXSK3mEv0DcwXJ1BWTBE0TdcARxVBdM+VUGo4rnsgK5kWollYhcft1WQpIcY2OLq91Z0ZCoFZYLK8g64mhF7a0S3nmJWp2EP4Fwy4vZBnvGqbsd2YvjIhV8S0t90tyVifWhVyf93y/vNwGnm7KRicISOLR3M7+4j2qR7sGg/bkatwEumKdsD7iTj88R64YxS6l3dgJm900sv99RXueyApR/09JXay5RDuTjl0/su0agSG0o=
  - secure: WPHkGtxfGy2tgszfkEEkMm4HNzkhN0Cb9cmcuyeruVr1HLtQPRkYoxCJo0T0pdVFRYaRt7Uwsj8uvzEYAn26U3dCP06KrT/pW3Sz6X/cXG1G33Aqs+fJM9L6O/nIv4ZXPdgNhyNssodgx3IkYwANrhJ0ZxmSaaQpqfGBMeh9y75ZOxUxs/L1tOFc0lQE2az8S1bI9eyvADCTHT/LS/7mpucKzVls3j9P7pZ7ZB/bdZf6CaCFUu+439H3wcDVq/+sJME74Y8iiKz4bcbNg1p2MrkrIHnNPsczajMGqzPYHJ20+Gm94tkwW70p/krwTh2/DDDA4P0rbVVT/OXpD+Ut30wyrnGdcvMuPTS1s0dCUIW9yA6zcdsD07Glj1tou11xk/6LaWL6gQY32nVgsG3r4gkrc2rioPxCyo4DWPNn8WLwkCVIwjO1CzqwsQ7VXE7f+/eGjktPY0JuNrS565IWGSOJBWUQFkSINLKdcWNv3RZcin3uluAj5AgliiWVrEpc2wy8LvgPSuPpgZIu/s3yJcZv1U8fWYjNFARiGh86r9/IfAWpRkNa84BoClmn5JPmGD/O1Qb8QSqP5WsjXrj/kZWmDC03D6O7aJAHc8j+hFMHSsOtCJeXnPLvPvZEpBA1vtLNXePAgRyH+5nhlH43vY0SLvlKgvAf3h6YY4sXZQg=
