desc "Submit to Google Play Alpha"
lane :submit_playalpha do

  upload_to_play_store(
    track: "alpha",
    apk: "cruzall/build/app/outputs/apk/release/app-release.apk"
  )

end


lane :screenshots do
  upload_to_play_store
end
